import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import type { FormEvent } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const [idText, setIdText] = useState<string>("");
  const router = useRouter();

  const joinGame = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    router.push(`/game/${idText.toLowerCase()}`);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen bg-black ">
        <form
          className="m-auto flex h-full w-full max-w-md flex-col justify-center gap-6 text-center align-middle"
          onSubmit={joinGame}
        >
          <input
            className="p-2 text-center text-2xl uppercase"
            autoComplete="off"
            placeholder="ID"
            maxLength={6}
            required={true}
            onChange={(e) => setIdText(e.target.value)}
          />
          <input
            className="bg-white p-4 text-2xl font-bold hover:cursor-pointer"
            type="submit"
            value="Join Game"
          />
        </form>
      </main>
    </div>
  );
};

export default Home;
