import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import type { FormEvent } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const [idText, setIdText] = useState<string>("");
  const router = useRouter();

  const joinGame = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    router.push(`/game/${idText.toLowerCase()}`);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black w-screen h-screen ">
        <form
          className="w-full h-full flex flex-col gap-6 align-middle justify-center text-center max-w-md m-auto"
          onSubmit={joinGame}
        >
          <input
            className="text-2xl text-center p-2 uppercase"
            autoComplete="off"
            placeholder="ID"
            maxLength={6}
            required={true}
            onChange={(e) => setIdText(e.target.value)}
          />
          <input
            className="bg-white p-4 hover:cursor-pointer text-2xl font-bold"
            type="submit"
            value="Join Game"
          />
        </form>
      </main>
    </div>
  );
};

export default Home;
