import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black w-screen h-screen flex">
        <div className="m-auto">
          <Link href="/game">
            <div className="bg-white p-4 hover:cursor-pointer">Play</div>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
