import type { NextPage } from "next";
import Head from "next/head";
import dynamic from "next/dynamic";
const Game = dynamic(() => import("../../components/game"), {
  ssr: false,
});

const GamePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Game />
    </div>
  );
};

export default GamePage;
